# These are supported funding model platforms

github: [Just-Chakal]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [https://paypal.me/thechakal, https://discord.gg/FwdBFreVyy]# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
